{% set name = "yte" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c94a0223f04e4661a41824d7fba087340b8ac87397f6dc385ee34499832ed5c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]
  entry_points:
    - yte = yte:main

requirements:
  host:
    - python
    - pip
    - poetry
    - plac
    - pyyaml
  run:
    - python
    - plac
    - pyyaml

test:
  imports:
    - yte
  requires:
    - pip
  commands:
    - pip check
    - yte --help
    - "echo -e '?if True:\n  foo: 1' | yte"  # [not win]

about:
  home: https://github.com/koesterlab/yte
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: YAML template engine
  # The remaining entries in this section are optional, but recommended.
  description: |
    YTE is a template engine for YAML format that utilizes the YAML 
    structure in combination with Python expressions for enabling to 
    dynamically build YAML documents.
  doc_url: https://github.com/koesterlab/yte
  dev_url: https://github.com/koesterlab/yte

extra:
  recipe-maintainers:
    - johanneskoester
    - fxwiegand
